Dev:
  'cert_file': '<cert file path - relative_path>'
  'vault':
    'vault_uri': '<vault url>'
    'vault_token': '<vault token - can be specified at run time or set in the environment>'
    'vault_path': '<vault path - can be specified at run time or set in the environment>'